# Generated by Django 4.2.4 on 2023-08-12 16:23

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_conversation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationVector",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("compiled", models.TextField()),
                ("vector", pgvector.django.VectorField(verbose_name=1024)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vectors", to="db.conversation"
                    ),
                ),
            ],
            options={
                "db_table": "conversation_vector",
                "ordering": ["-created_at"],
            },
        ),
    ]
