# Generated by Django 4.2.4 on 2023-09-11 17:01

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_conversationvector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationvector",
            name="vector",
            field=pgvector.django.VectorField(dimensions=1024),
        ),
    ]
