# Generated by Django 4.2.4 on 2023-11-25 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_conversationvector_vector_index"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConversationVector",
        ),
    ]
